// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCNxBZ-lzkWmAnUeS3Vz33OTRf0SrPo1Q',
    appId: '1:277584985704:web:5c28494c4cb2e22ccb45dd',
    messagingSenderId: '277584985704',
    projectId: 'flutter-phone-auth-5a157',
    authDomain: 'flutter-phone-auth-5a157.firebaseapp.com',
    storageBucket: 'flutter-phone-auth-5a157.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2tk7FkhdE6p3h25jrtW4dG4AO9iVgVhA',
    appId: '1:277584985704:android:e379f17ebcf2cadfcb45dd',
    messagingSenderId: '277584985704',
    projectId: 'flutter-phone-auth-5a157',
    storageBucket: 'flutter-phone-auth-5a157.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUAszSGbNbv1opR3zSR62n9DemU2Tc5lg',
    appId: '1:277584985704:ios:609ebf4c2908041dcb45dd',
    messagingSenderId: '277584985704',
    projectId: 'flutter-phone-auth-5a157',
    storageBucket: 'flutter-phone-auth-5a157.appspot.com',
    iosBundleId: 'com.example.flutterPhoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUAszSGbNbv1opR3zSR62n9DemU2Tc5lg',
    appId: '1:277584985704:ios:609ebf4c2908041dcb45dd',
    messagingSenderId: '277584985704',
    projectId: 'flutter-phone-auth-5a157',
    storageBucket: 'flutter-phone-auth-5a157.appspot.com',
    iosBundleId: 'com.example.flutterPhoneAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCNxBZ-lzkWmAnUeS3Vz33OTRf0SrPo1Q',
    appId: '1:277584985704:web:b5439dd117d006c4cb45dd',
    messagingSenderId: '277584985704',
    projectId: 'flutter-phone-auth-5a157',
    authDomain: 'flutter-phone-auth-5a157.firebaseapp.com',
    storageBucket: 'flutter-phone-auth-5a157.appspot.com',
  );

}